wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707893672.365218
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 14
      - 23
      4: 3.10.13
      5: 0.16.2
      8:
      - 1
      - 5
      9:
        2: Avalanche
      13: linux-x86_64
